/**
 * Test hooks shared by components and automated suites.
 * Naming: `<component>-<element>[-<variant>]`. Identity never goes in here;
 * use a separate attribute such as `data-show-id`, `data-genre` or `data-kind`.
 */
export const TEST_IDS = {
  skipLink: 'skip-link',
  appHeader: 'app-header',
  appBrand: 'app-brand',
  appFooter: 'app-footer',
  appNav: 'app-nav',
  navAllGenres: 'nav-all-genres',
  navBookmarked: 'nav-bookmarked',
  navLiked: 'nav-liked',
  themeToggle: 'theme-toggle',
  searchField: 'search-field',
  genreSelect: 'genre-select',
  dashboardPage: 'dashboard-page',
  dashboardSkeleton: 'dashboard-skeleton',
  dashboardStatus: 'dashboard-status',
  dashboardRows: 'dashboard-rows',
  genreRow: 'genre-row',
  genreRowHeading: 'genre-row-heading',
  genreRowProgress: 'genre-row-progress',
  genreRowSkeleton: 'genre-row-skeleton',
  genreRowSkeletonHeading: 'genre-row-skeleton-heading',
  genreRowExpand: 'genre-row-expand',
  genreGrid: 'genre-grid',
  genreGridHeading: 'genre-grid-heading',
  genreGridClose: 'genre-grid-close',
  genreGridCount: 'genre-grid-count',
  moreShows: 'more-shows',
  moreShowsButton: 'more-shows-button',
  moreShowsEnd: 'more-shows-end',
  deferredBlock: 'deferred-block',
  scrollRow: 'scroll-row',
  scrollRowList: 'scroll-row-list',
  scrollRowPrev: 'scroll-row-prev',
  scrollRowNext: 'scroll-row-next',
  scrollRowLoading: 'scroll-row-loading',
  rowPages: 'row-pages',
  rowPagesPage: 'row-pages-page',
  rowPagesRange: 'row-pages-range',
  showCard: 'show-card',
  showCardLink: 'show-card-link',
  showCardBookmark: 'show-card-bookmark',
  showCardLike: 'show-card-like',
  saveToggle: 'save-toggle',
  showPoster: 'show-poster',
  showPosterImage: 'show-poster-image',
  showPosterFallback: 'show-poster-fallback',
  ratingBar: 'rating-bar',
  ratingMark: 'rating-mark',
  genreChip: 'genre-chip',
  showFacts: 'show-facts',
  showSummary: 'show-summary',
  skeletonCard: 'skeleton-card',
  appIcon: 'app-icon',
  appButton: 'app-button',
  iconButton: 'icon-button',
  errorPanel: 'error-panel',
  errorPanelRetry: 'error-panel-retry',
  emptyState: 'empty-state',
  emptyStateAction: 'empty-state-action',
  showGrid: 'show-grid',
  showDetailPage: 'show-detail-page',
  showDetailBack: 'show-detail-back',
  showDetailChips: 'show-detail-chips',
  showDetailBookmark: 'show-detail-bookmark',
  showDetailLike: 'show-detail-like',
  showDetailSource: 'show-detail-source',
  searchPage: 'search-page',
  searchCount: 'search-count',
  savedShowsPage: 'saved-shows-page',
  savedShowsGrid: 'saved-shows-grid',
  savedShowsEmpty: 'saved-shows-empty',
  notFoundPage: 'not-found-page',
} as const;

export type TestId = (typeof TEST_IDS)[keyof typeof TEST_IDS];
